### ISSUE TITLE
Fatal error: Call to undefined method ZfcUserDoctrineORM\Mapper\User::findAll()

### ISSUE THREAD

**Issue by webdevilopers** [Danielss89/ZfcUserAdmin#20]
in .../vendor/ZfcUserAdmin/src/ZfcUserAdmin/Controller/UserAdminController.php on line 16
though all my dependencies seem up to date.

Am I missing something?

**Comment by Hounddog** [comment]
No you are not missing anything here. The module is still under development and this is a bug which i can confirm.

**Comment by webdevilopers** [comment]
Anything new @Hounddog ?

**Comment by Hounddog** [comment]
I have not been able to continue work on this module yet and i am afraid it will take some more time for me to get back to it.

**Comment by webdevilopers** [comment]
Too bad @Hounddog ! Are there any alternatives for administrating ZfcUser? Good luck!

**Comment by webdevilopers** [comment]
Closed = solved @Danielss89 , @Hounddog ?

**Comment by alex-jgr** [comment]
Got over this issue recently. In the file "/zfc-user-admin/config/services.config.php" rename the factory "zfcuser_user_mapper" to "zfcuseradmin_user_mapper". Also use the new name in the module's controller on line 134. 
"zfcuser_user_mapper" from this module is not being used because the factory is already declared in the ZfcUserDoctrineORM module.
